# Generated by Django 4.2.7 on 2026-06-10 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HormoneReservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hormone_type', models.CharField(max_length=100)),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('low_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hormone Reservoir',
                'verbose_name_plural': 'Hormone Reservoirs',
                'db_table': 'hormone_reservoirs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HormoneRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hormone_releases', to='animals.animal')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hormone_releases', to=settings.AUTH_USER_MODEL)),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='hormones.hormonereservoir')),
            ],
            options={
                'verbose_name': 'Hormone Release',
                'verbose_name_plural': 'Hormone Releases',
                'db_table': 'hormone_releases',
                'ordering': ['-timestamp'],
            },
        ),
    ]
