# Generated by Django 4.2.7 on 2026-07-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hormones', '0003_hormoneschedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hormonerelease',
            new_name='hormone_rel_timesta_bdfd33_idx',
            old_name='hormone_rel_timesta_4e861a_idx',
        ),
    ]
