# Generated by Django 4.2.7 on 2026-06-10 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('low_hormone', 'Low Hormone Level'), ('device_disconnection', 'Device Disconnection'), ('low_battery', 'Low Battery'), ('abnormal_reading', 'Abnormal Reading'), ('missed_schedule', 'Missed Schedule')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('related_entity_type', models.CharField(max_length=50)),
                ('related_entity_id', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['status', '-timestamp'], name='alerts_status_6a72b8_idx'), models.Index(fields=['alert_type', 'severity'], name='alerts_alert_t_cb4af9_idx')],
            },
        ),
    ]
