# Generated by Django 4.2.7 on 2026-06-10 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treatment Protocol',
                'verbose_name_plural': 'Treatment Protocols',
                'db_table': 'treatment_protocols',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_assignments', to='animals.animal')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='protocols.treatmentprotocol')),
            ],
            options={
                'verbose_name': 'Treatment Assignment',
                'verbose_name_plural': 'Treatment Assignments',
                'db_table': 'treatment_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('description', models.TextField()),
                ('hormone_type', models.CharField(max_length=100)),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_offset', models.IntegerField()),
                ('time_of_day', models.TimeField()),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='protocols.treatmentprotocol')),
            ],
            options={
                'verbose_name': 'Protocol Step',
                'verbose_name_plural': 'Protocol Steps',
                'db_table': 'protocol_steps',
                'ordering': ['protocol', 'step_number'],
                'unique_together': {('protocol', 'step_number')},
            },
        ),
    ]
