# Generated by Django 4.2.7 on 2026-07-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_treatmentassignment_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='treatmentassignment',
            new_name='treatment_a_status_e362c9_idx',
            old_name='treatment_a_status_467ee7_idx',
        ),
        migrations.RenameIndex(
            model_name='treatmentassignment',
            new_name='treatment_a_start_d_48685f_idx',
            old_name='treatment_a_start_d_a5e9f8_idx',
        ),
    ]
