# Generated by Django 4.2.7 on 2026-06-10 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('under_treatment', 'Under Treatment')], default='healthy', max_length=50)),
                ('reproductive_status', models.CharField(choices=[('pregnant', 'Pregnant'), ('cycling', 'Cycling'), ('not_cycling', 'Not Cycling')], max_length=50)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'db_table': 'animals',
                'ordering': ['-created_at'],
            },
        ),
    ]
