# Generated by Django 4.2.7 on 2026-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Body Temperature'), ('movement', 'Movement Level')], max_length=50),
        ),
    ]
