# Generated by Django 4.2.7 on 2026-06-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='module_accessed',
            field=models.CharField(blank=True, choices=[('dashboard', 'Dashboard'), ('animals', 'Animals'), ('devices', 'Devices'), ('monitoring', 'Monitoring'), ('hormones', 'Hormones'), ('protocols', 'Protocols'), ('alerts', 'Alerts'), ('reports', 'Reports'), ('profile', 'Profile')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('generate_report', 'Generate Report'), ('download_pdf', 'Download PDF'), ('alert_action', 'Alert Action')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['module_accessed', '-timestamp'], name='activity_lo_module__999652_idx'),
        ),
    ]
